[MockHardware] Enable disabling of command to simulate HW failures.
ros-controls/ros2_control pull request #1027
Opened 2023-05-17 00:38 UTC by destogl

1. part of the port from #540.

2023-05-17 19:53 UTC, christophfroehlich requested changes
LGTM, but please add this option to the docs

2023-05-19 10:38 UTC, bmagyar submitted a review, later dismissed
Looks good but agree w @christophfroehlich

2023-05-22 06:45 UTC, livanov93 submitted a review, later dismissed
Looks good!

2023-05-26 05:28 UTC, destogl commented
OK, will add docs and then merge.

2023-05-31 20:34 UTC, christophfroehlich commented on hardware_interface/doc/mock_components_userdoc.rst
> +  Or it can help you to test your setup when the hardware is running without feedback, i.e., in the open loop.
```suggestion
  Or it can help you to test your setup when the hardware is running without feedback, i.e., in open loop configuration.
```

2023-06-04 18:25 UTC, bmagyar approved these changes

2023-06-04 18:25 UTC, merged