Issue 759: This will add the cleanup service
ros-controls/ros2_control pull request #1236
Opened 2023-12-18 13:42 UTC by bailaC

2023-12-18 13:43 UTC, closed without merging

2023-12-18 13:47 UTC, bailaC commented
@destogl Please check the draft PR. I think the main logic of the transition is missing. I will check again at my end.

2023-12-18 18:10 UTC, saikishor commented
Hello @bailaC,

After looking roughly at the `cleanup_controller` service, it seems to me similar to the `unload_controller` service that exist in the controller manager.

https://github.com/ros-controls/ros2_control/blob/89c8658a3419e4d23aea37eda7b17a0d1eecb840/controller_manager/src/controller_manager.cpp#L601-L661

What do you think?

2023-12-18 18:10 UTC, saikishor reviewed
Hello @bailaC,

After looking roughly at the `cleanup_controller` service, it seems to me similar to the `unload_controller` service that exist in the controller manager.

https://github.com/ros-controls/ros2_control/blob/89c8658a3419e4d23aea37eda7b17a0d1eecb840/controller_manager/src/controller_manager.cpp#L601-L661

What do you think?

2024-01-22 15:14 UTC, destogl reviewed
@bailaC can you please write tests for the newly added code.

2024-02-02 17:58 UTC, saikishor requested changes
Apart from the following changes, I want to know your opinion @destogl @bailaC on the following

Does it make sense to call the service alone `unconfigure_controller` instead of `cleanup_controller` (We can leave the rest of the methods without renaming as internally it's fine)?. Because it might give more or less the basic idea of the service in the context of controllers.

2025-04-17 13:24 UTC, soham2560 commented
suggested method to commit to this pr? can I directly push to [StoglRobotics-forks:issue-759](https://github.com/StoglRobotics-forks/ros2_control/tree/issue-759) or create a PR targetting it instead

2025-04-17 19:02 UTC, christophfroehlich commented
> @christophfroehlich suggested method to commit to this pr? should I create a PR targetting StoglRobotics-forks:issue-759](https://github.com/StoglRobotics-forks/ros2_control/tree/issue-759) or something else

First, get familiar with the code and discuss the open points of this PR above. Then, create a fork of StoglRobotics-forks:issue-759, but open a PR against ros-controls:master. So the original authors of the earlier commits will remain, and we'll just close this PR here.

2025-05-29 04:25 UTC, soham2560 commented
> Apart from the following changes, I want to know your opinion @destogl @bailaC on the following
 Does it make sense to call the service alone unconfigure_controller instead of cleanup_controller (We can leave the rest of the methods without renaming as internally it's fine)?. Because it might give more or less the basic idea of the service in the context of controllers.
 
@saikishor  considering the conversation at https://github.com/ros-controls/ros2_control/pull/2163 would you say `cleanup_controller` as a name for the service would be fine now? since the state it goes to is clarified by the paranthesis addition in gui

2025-05-29 04:34 UTC, soham2560 commented on controller_manager/src/controller_manager.cpp
> +  }
makes sense actually, I will change it once we clear up the prior conversations

2025-07-27 10:47 UTC, soham2560 commented
Have added draft PR at https://github.com/ros-controls/ros2_control/pull/2414 as suggested in https://github.com/ros-controls/ros2_control/pull/1236#issuecomment-2813793729, some changes remaining but is ready to for a look.

@saikishor I will be making the `unconfigure_controller` changes we talked about, however what about the other suggestions you have put up, I agree with most of them, should I make the changes directly in #2414 or would you like to do a full review there directly?

2025-07-28 05:58 UTC, christophfroehlich commented
Closing in favor of #2414

2025-07-28 12:40 UTC, saikishor commented
> Have added draft PR at #2414 as suggested in [#1236 (comment)](https://github.com/ros-controls/ros2_control/pull/1236#issuecomment-2813793729), some changes remaining but is ready to for a look.
> 
> @saikishor I will be making the `unconfigure_controller` changes we talked about, however what about the other suggestions you have put up, I agree with most of them, should I make the changes directly in #2414 or would you like to do a full review there directly?

Yes, please apply them :)