[CI] Add ABI check for rolling
ros-controls/ros2_control pull request #1300
Opened 2024-01-16 19:59 UTC by christophfroehlich

Is there any particular reason why there is no ABI check workflow for rolling?

Furthermore, within ros2_controllers repo we test against `ROS_REPO: testing`. Which is the correct one here?

2024-01-17 12:43 UTC, destogl commented
I would say that is almost the same if we use `main` or `testing`. We want to generally see if we are breaking stuff against the released packages. `main` is released, and `testing` is to be released.

We don't have an ABI check for rolling since it takes a long and it is not necessary there. We can break ABI in rolling without any considerations. So I would keep it out.

2024-01-17 12:43 UTC, destogl requested changes
I don't think we need this changes here.

2024-01-17 15:24 UTC, christophfroehlich commented
The only thing why it could be useful is to see if a PR can/should be backported. If it breaks ABI on rolling, probably not.

2024-01-17 15:53 UTC, destogl commented
> The only thing why it could be useful is to see if a PR can/should be backported. If it breaks ABI on rolling, probably not.

I think we should decide that base don functionality. Breaking ABI on rolling doesn't tell us much about ABI in `humble` and `iron` anymore.

2024-01-17 17:18 UTC, christophfroehlich commented
> I think we should decide that base don functionality. Breaking ABI on rolling doesn't tell us much about ABI in `humble` and `iron` anymore.

sure. it would be only a little help, if it breaks _already_ on rolling, it breaks for sure on the others.

2024-01-18 17:40 UTC, destogl commented
> > I think we should decide that base don functionality. Breaking ABI on rolling doesn't tell us much about ABI in `humble` and `iron` anymore.
> 
> sure. it would be only a little help, if it breaks _already_ on rolling, it breaks for sure on the others.

That is my point: not necessary. We could have already broken ABI on `rolling` and on old branches will not be broken. A typical case would be that we have removed a member variable and now we have to introduce again. Variables are most common for ABI breaking.

@bmagyar what do you think? If you want just merge it

2024-01-22 12:33 UTC, merged