[CM] Remove deprecated parameters for initial component states.
ros-controls/ros2_control pull request #1357
Opened 2024-02-01 19:32 UTC by destogl

- Remove deprecated parameters and warning about getting robot descritpion from parameter.
- Remove old parameter from tests.

2024-02-01 19:47 UTC, destogl commented on controller_manager/src/controller_manager.cpp
> -      "is deprecated. Use '~/robot_description' topic from 'robot_state_publisher' instead.");
```suggestion
RCLCPP_WARN(
      get_logger(),
      "[Deprecated] Passing the robot description parameter directly to the control_manager node "
      "is deprecated. Use '~/robot_description' topic from 'robot_state_publisher' instead.");
```

2024-02-01 21:21 UTC, fmauch requested changes
I could not thoroughly test this, but that compile issue is definitively there.

2024-02-01 21:21 UTC, fmauch commented on controller_manager/src/controller_manager.cpp
> +    resource_manager_->set_component_state(component, active_state);
```suggestion
    rclcpp_lifecycle::State active_state(
      State::PRIMARY_STATE_ACTIVE, hardware_interface::lifecycle_state_names::ACTIVE);
    resource_manager_->set_component_state(component, active_state);
```

2024-02-02 16:44 UTC, destogl commented on controller_manager/src/controller_manager.cpp
> +    resource_manager_->set_component_state(component, active_state);
Thanks!

2024-02-02 18:29 UTC, fmauch approved these changes
Verified that I could still successfully configure initial component state with this.

2024-02-28 09:15 UTC, saikishor approved these changes
LGTM

2024-02-28 17:09 UTC, merged