Added spawner colours to `list_controllers` depending upon active or inactive
ros-controls/ros2_control pull request #1409
Opened 2024-02-21 11:23 UTC by soham2560

### This PR
Closes #687
- Made output for list_controllers coloured
  - Active controllers are highlighted with green `active`
  - Inactive controllers are highlighted with red `inactive`

### Screenshots
![image](https://github.com/ros-controls/ros2_control/assets/116435641/70333f16-8d7b-48cc-ba97-a7f50ebbe165)

2024-02-21 11:46 UTC, christophfroehlich commented
Thanks for the nice addon. Should we add other colors for unconfigured state? It is printed in red now, if it is in any other state than active?

2024-02-21 12:10 UTC, soham2560 commented on ros2controlcli/ros2controlcli/verb/list_controllers.py
> +    state_color = bcolors.OKGREEN if c.state == "active" else bcolors.FAIL
Yes, I think that makes much more sense. I'll make the necessary changes

2024-02-21 12:14 UTC, olivier-stasse requested changes

2024-02-21 13:40 UTC, soham2560 commented
I have changed the color scheme in [7be93b2](https://github.com/ros-controls/ros2_control/pull/1409/commits/7be93b2311e836509671ff37ebf24f9f1e3af43e). However 2 points
- I wasn't able to test this with a controller in the unconfigured state as I couldn't find a way to set that state purposefully, if you know of a way do let me know, I will test for that too
- We also haven't considered the finalized state, should I add that too?

2024-02-21 13:44 UTC, soham2560 commented on ros2controlcli/ros2controlcli/verb/list_controllers.py
> +    state_color = bcolors.OKGREEN if c.state == "active" else bcolors.FAIL
refer https://github.com/ros-controls/ros2_control/pull/1409#issuecomment-1956676886

2024-02-21 17:27 UTC, saikishor commented
> * I wasn't able to test this with a controller in the unconfigured state as I couldn't find a way to set that state purposefully, if you know of a way do let me know, I will test for that too

If you load a controller using `load_controller` service then it goes into unconfigured state
 
> * Current code also doesn't consider the finalized state, should I add that too?

I think internally it is not linked to any controller state, so I belive it should be good

2024-02-21 20:05 UTC, christophfroehlich commented
Fyi, you can use rqt_controller_manager to set the state of a controller easily.
Have a look at this color scheme here:
https://github.com/ros-controls/ros2_control/blob/c4affe4bbfbb12b947acfc7b268f529724e0aae8/rqt_controller_manager/rqt_controller_manager/controller_manager.py#L87-L93
maybe we can use the same colors there as you have implemented it now?

2024-02-21 21:44 UTC, fmauch approved these changes
I like the improvement!

2024-02-22 04:49 UTC, soham2560 commented
Thanks for the tips regarding the controller manager @saikishor @christophfroehlich! Was able to test with the unconfigured state as well, I've added the result in the PR description, do have a look.

>maybe we can use the same colors there as you have implemented it now?

That sounds like a good idea, I can have a look at that if you want

2024-02-23 05:49 UTC, olivier-stasse approved these changes

2024-02-23 08:42 UTC, saikishor approved these changes
LGTM

2024-02-28 17:10 UTC, destogl approved these changes

2024-02-29 16:50 UTC, bmagyar approved these changes

2024-02-29 16:51 UTC, merged