Add key-value-storage to the IntefaceInfo
ros-controls/ros2_control pull request #1421
Opened 2024-02-27 17:58 UTC by mamueluth

This PR adds the possibility to define custom parameters (key-value-storage) per Interface (Commad-/StateInterface). This is useful to define a .ros2_conrtrol.xacro for a hardware driver that uses for example Modbus for communication. In this case, you want to be able to define e.g. which register is used to retrieve/write the data for each Command-/StateInteface Individually.

Has been tested and works. Test have been added. 

The exception as been altered as I did some mistake while defining the URDF and the thrown exception "invalid URDF passed in to robot parser" is not very useful at all. I would prefer this to be merged  as it now gives some useful hint what was gone wrong. If i should move  the two lines of code to an other PR as its not really related please let me know.

2024-04-24 16:19 UTC, christophfroehlich requested changes
This looks valuable and the implementation is straight forward, thanks!

Just one usual comment from my side, please add this to the docs:

- [ ] maybe [here](https://control.ros.org/master/doc/ros2_control/hardware_interface/doc/hardware_interface_types_userdoc.html) or create a new page.
- [ ] into the [release notes](https://github.com/ros-controls/ros2_control/pull/1477/files#diff-0c007bfed7d9684b385392a2b58811b75b952bb7702b2571a6f84d2e0cd9e602). If it get not merged soon, just comment here and I'll add that later.

2024-04-24 16:20 UTC, christophfroehlich commented
@mamueluth can you please rebase this on master to run the checks? (we can't do that because this PR comes from an organization)

2024-04-29 12:46 UTC, christophfroehlich commented
Fyi, CI looks good but codecov needs https://github.com/ros-controls/ros2_control/pull/1504 and the other failures are already reported  https://github.com/ros-controls/ros2_control/issues/1367 and not related imho.

2024-05-22 09:06 UTC, mamueluth commented
@christophfroehlich  I added a overview to the docs. There the key-value storage is described in a generic example. We could explain the other xml tags there as well.
Release notes let me know if i should add.

2024-08-16 11:49 UTC, destogl commented on hardware_interface/doc/hardware_interface_types_userdoc.rst
> +          <!-- All of them are optional. Data_type and size are used for GPIOs. Size length of array. -->
```suggestion
          <!-- All of them are optional. `data_type` and `size` are used for GPIOs. Size is length of an array. -->
```

2024-08-16 12:16 UTC, destogl approved these changes
Very nice, thanks!

2024-08-16 12:21 UTC, destogl approved these changes

2024-08-16 12:30 UTC, destogl submitted a review, later dismissed

2024-08-16 15:29 UTC, saikishor approved these changes
Very nice!
Nice tests too!
Thanks for the nice work

2024-08-16 15:29 UTC, saikishor commented on hardware_interface/doc/hardware_interface_types_userdoc.rst
> +You can check this classes to see what attributes are available for each of the xml tags.
```suggestion
You can check this struct to see what attributes are available for each of the xml tags.
```

2024-08-19 07:22 UTC, mamueluth commented on hardware_interface/doc/hardware_interface_types_userdoc.rst
> +You can check this classes to see what attributes are available for each of the xml tags.
```suggestion
You can check the structs defined there to see what attributes are available for each of the xml tags.
```

2024-08-26 17:25 UTC, destogl submitted a review, later dismissed

2024-08-26 18:13 UTC, bmagyar commented on hardware_interface/include/hardware_interface/hardware_info.hpp
> +  /// interface needs own address(register), datatype, ...
```suggestion
  /// interface needs own address(register), datatype, etc.
```

2024-08-28 07:41 UTC, destogl approved these changes

2024-08-28 07:50 UTC, bmagyar approved these changes

2024-08-28 08:38 UTC, christophfroehlich requested changes
A short note in the release notes would be great 😇

2024-08-28 08:42 UTC, christophfroehlich approved these changes
(sorry for being late, we can add the release notes in a follow-up PR as well).

2024-08-28 09:47 UTC, mamueluth commented
> A short note in the release notes would be great 😇

done

2024-08-28 10:37 UTC, saikishor requested changes
A minor detail

2024-08-28 10:37 UTC, saikishor commented on doc/release_notes.rst
> +
```suggestion
* With (`#1683 <https://github.com/ros-controls/ros2_control/pull/1683>`_) the ``rclcpp_lifecycle::State & get_state()`` and ``void set_state(const rclcpp_lifecycle::State & new_state)`` are replaced by ``rclcpp_lifecycle::State & get_lifecycle_state()`` and ``void set_lifecycle_state(const rclcpp_lifecycle::State & new_state)``. This change affects controllers and hardware. This is related to (`#1240 <https://github.com/ros-controls/ros2_control/pull/1240>`_) as variant support introduces ``get_state`` and ``set_state`` methods for setting/getting state of handles.
* With (`#1421 <https://github.com/ros-controls/ros2_control/pull/1421>`_) a key-value storage is added to InterfaceInfo. This allows to define extra params with per Command-/StateInterface in the ``.ros2_control.xacro`` file.

```

2024-08-28 14:46 UTC, saikishor approved these changes

2024-08-28 17:08 UTC, merged