[Feature] Hardware Components Grouping
ros-controls/ros2_control pull request #1458
Opened 2024-03-24 21:46 UTC by saikishor

This PR allows to have hardware component grouping to allow the components to propagate errors between each other. This is very helpful if the hardware components of one of the actuator of a manipulator fails, we can propagate the error to the rest of the actuators by grouping all their hardware components to one group. In this way, we could avoid continue to execute the motion 

Closes https://github.com/ros-controls/ros2_control/issues/1457

2024-03-24 22:06 UTC, saikishor commented
The failing tests are due to the Flake8 issue :)

2024-03-25 07:29 UTC, christophfroehlich approved these changes
LGTM, and thanks for updating the docs as well :grin:

2024-05-12 13:14 UTC, christophfroehlich submitted a review, later dismissed

2024-05-20 18:19 UTC, bmagyar requested changes

2024-05-20 18:19 UTC, bmagyar commented on hardware_interface/doc/hardware_interface_types_userdoc.rst
> +Hardware Component Groups play a vital role in propagating errors across interconnected hardware components. For instance, in a manipulator system, grouping actuators together allows for error propag
```suggestion
Hardware Component Groups play a vital role in propagating errors across interconnected hardware components. For instance, in a manipulator system, grouping actuators together allows for error propagation. If one actuator fails within the group, the error can propagate to the other actuators, signaling a potential issue across the system. By default, the actuator errors are isolated to their own hardware component, allowing the rest to continue operation unaffected. In the provided ros2_control configuration, the ``<group>`` tag within each ``<ros2_control>`` block signifies the grouping of hardware components, enabling error propagation mechanisms within the system.
```

2024-05-20 18:19 UTC, bmagyar commented on hardware_interface/src/resource_manager.cpp
> +    if (value > hw_group_state_.at(group_name))
```suggestion
    if (value != return_type::OK)
```
the docs clearly say what you wanted to write in code here ;) 
>  // If it is anything other than OK

2024-05-22 17:37 UTC, bmagyar approved these changes

2024-05-22 17:38 UTC, merged