Parse URDF soft_limits into the HardwareInfo structure
ros-controls/ros2_control pull request #1488
Opened 2024-04-18 11:31 UTC by adriaroig

Needs to be merged after #1472

This PR allows to parse the soft_limits into the HardwareInfo structure, so that this can be later reused by the ResourceManager to enforce the limits on the JointCommandInterfaces.

In the test, it is checked that the soft_limits uses the most restrictive value between the soft_limits and the generic limits.

2024-04-23 21:43 UTC, christophfroehlich submitted a review, later dismissed
LGTM, thanks!

2024-05-07 19:55 UTC, christophfroehlich requested changes
My usual comment: please update the docs ;) in this case the release notes should be fine, we haven't documented the structure elsewhere.

2024-05-07 20:36 UTC, christophfroehlich approved these changes
Thanks!

2024-05-09 11:23 UTC, bmagyar approved these changes

2024-05-09 11:23 UTC, merged