Fix the namespaced controller_manager spawner + added tests
ros-controls/ros2_control pull request #1640
Opened 2024-07-24 21:19 UTC by saikishor

This PR aims to fix the spawner to work with namespace controller manager and added tests for this particular case. It is started from #1547, however after looking into the spawner, it seems like the `--namespace` parameter is no longer required as you could pass it in the arg `--controller-manager` as how it is done for the unspawner, if this is fine, then we can get rid of the `--namespace` arg 

closes: #1547
fixes: #1506

2024-07-26 11:51 UTC, christophfroehlich requested changes
Tested with https://github.com/ros-controls/ros2_control_demos/pull/502 but I still failed.

2024-07-27 10:31 UTC, bmagyar requested changes
Sounds like a good idea but let's deprecate the namespace parameter first, loudly

2024-07-27 10:33 UTC, saikishor commented
> Sounds like a good idea but let's deprecate the namespace parameter first, loudly

Make sense. You are right. I shouldn't have removed it abruptly hahHa 😅😅

2024-07-27 13:05 UTC, saikishor commented
@bmagyar I've added the `--namespace` arg is now added as deprecated and I've also added tests for the deprecated arg

@christophfroehlich I've made some changes on https://github.com/ros-controls/ros2_control_demos/pull/502 for the new namespacing and also the missing `--param-file` arg. Check and let me know

2024-07-29 08:16 UTC, christophfroehlich requested changes
Tested now successfully with [1ac5e13](https://github.com/ros-controls/ros2_control_demos/pull/502/commits/1ac5e139a371d1037c974698599ab653b6f87ef9) of https://github.com/ros-controls/ros2_control_demos/pull/502.

May I ask for updating the [docs](https://github.com/ros-controls/ros2_control/blob/master/controller_manager/doc/userdoc.rst#helper-scripts), and adding migration notes?

2024-07-29 08:17 UTC, saikishor commented
> May I ask for updating the [docs](https://github.com/ros-controls/ros2_control/blob/master/controller_manager/doc/userdoc.rst#helper-scripts), and adding migration notes?

Sire, I can update the docs.

2024-07-29 09:21 UTC, christophfroehlich submitted a review, later dismissed
Thanks :)

2024-07-29 09:57 UTC, bmagyar commented on controller_manager/doc/userdoc.rst
> +                            Namespace for the controller_manager and the controller(s) (deprecated)
```suggestion
                            DEPRECATED Namespace for the controller_manager and the controller(s)
```

2024-07-29 17:08 UTC, bmagyar commented on controller_manager/controller_manager/spawner.py
> +        help="Namespace for the controller_manager and the controller(s) (deprecated)",
```suggestion
        help="DEPRECATED Namespace for the controller_manager and the controller(s)",
```

2024-07-29 17:09 UTC, bmagyar submitted a review, later dismissed

2024-07-29 18:02 UTC, merged