Add controller node options args to be able to set controller specific node arguments
ros-controls/ros2_control pull request #1713
Opened 2024-08-23 09:52 UTC by saikishor

A different approach of #1712

```
    robot_controller_spawner = Node(
        package="controller_manager",
        executable="spawner",
        arguments=["diffbot_base_controller", "--param-file", controller_config, "--controller-ros-args", '--ros-args -r /diffbot_base_controller/cmd_vel:=/cmd_vel'],
    )
```

Fixes: #1711

2024-08-23 19:10 UTC, christophfroehlich requested changes
I like, but needs some tests for it and advertisement in the release notes. We could also think of deprecating the "old way" #1712 

Tested successfully with https://github.com/ros-controls/ros2_control_demos/pull/577

2024-08-24 00:30 UTC, saikishor reviewed
Fix for compilation

2024-08-24 00:30 UTC, saikishor commented on controller_manager/src/controller_manager.cpp
> +  }
```suggestion
    !controller.info.node_options_args.empty() &&
    !check_for_element(controller.info.node_options_args, RCL_ROS_ARGS_FLAG)
  {
    node_options_arguments.push_back(RCL_ROS_ARGS_FLAG);
  }
```

2024-08-24 00:33 UTC, saikishor commented on controller_manager/src/controller_manager.cpp
> +  // Add options parsed through the spawner
I fixed with other to avoid using the hard-coded strings

2024-08-24 00:34 UTC, saikishor commented on controller_manager/src/controller_manager.cpp
> +    !check_for_element(controller.info.node_options_args, RCL_ROS_ARGS_FLAG)
```suggestion
    !check_for_element(controller.info.node_options_args, RCL_ROS_ARGS_FLAG))
```

2024-09-11 21:33 UTC, saikishor commented
> I like, but needs some tests for it and advertisement in the release notes. We could also think of deprecating the "old way" #1712
> 
> Tested successfully with [ros-controls/ros2_control_demos#577](https://github.com/ros-controls/ros2_control_demos/pull/577)

@christophfroehlich I've added the tests for this case and the release_notes.

Thank you!

2024-09-12 08:52 UTC, christophfroehlich submitted a review, later dismissed
thx

2024-10-17 10:27 UTC, saikishor commented
@bmagyar the CI seems to be happy

2024-10-29 18:20 UTC, christophfroehlich commented
I'll add `example_interfaces` to the debian image used for the CI.

2024-10-29 18:29 UTC, saikishor commented
> I'll add `example_interfaces` to the debian image used for the CI.

Thank you @christophfroehlich

2024-10-29 20:36 UTC, christophfroehlich submitted a review, later dismissed
LGTM (debian CI is happy now, too).

2024-11-06 18:48 UTC, christophfroehlich approved these changes

2024-12-09 19:47 UTC, bmagyar commented
Is this still needed?

2024-12-09 19:59 UTC, saikishor commented
> Is this still needed?

@bmagyar yes, we will still need it

2024-12-18 19:01 UTC, christophfroehlich approved these changes

2024-12-19 07:18 UTC, bmagyar approved these changes

2024-12-19 07:19 UTC, merged