[CM] Throw an exception when the components initially fail to be in the required state
ros-controls/ros2_control pull request #1729
Opened 2024-08-28 16:36 UTC by saikishor

We faced another bug during our testing when the HW component failed to configure at the beginning, the CM prints that the Resource Manager is successfully initialized and exposes it's internal services and the spawner calls are being processed on startup.

I believe, If the user's initial intent is supposed to be in a particular state, it is better to have failed when this is not the case rather than continue to expose services and then fail again. Usually, when the services are exposed, it is expected that HW components are successfully initialized.

2024-08-29 05:19 UTC, christophfroehlich approved these changes
LGTM! #1530

2024-08-29 08:31 UTC, Noel215 approved these changes
Tested on real hardware

2024-08-30 15:51 UTC, bmagyar commented on controller_manager/src/controller_manager.cpp
> +              "Failed to set the state of the component : " + component + " to " + state.label());
```suggestion
              "Failed to set the initial state of the component : " + component + " to " + state.label());
```

2024-08-30 15:51 UTC, bmagyar requested changes
just a small adjustment for people to be aware

2024-08-30 15:51 UTC, bmagyar commented on controller_manager/src/controller_manager.cpp
> +        "Failed to set the state of the component : " + component + " to " + active_state.label());
```suggestion
        "Failed to set the initial state of the component : " + component + " to " + active_state.label());
```

2024-08-30 15:52 UTC, bmagyar commented
Also... would a test for this be possible?

2024-08-30 15:54 UTC, saikishor commented
> Also... would a test for this be possible?

Yes! I'll add it when I address #1530. It's in my list. I wanted to do it once the variants and others are merged.

2024-08-30 16:35 UTC, christophfroehlich commented on controller_manager/src/controller_manager.cpp
> +              "Failed to set the initial state of the component : " + component + " to " + state.label());
```suggestion
              "Failed to set the initial state of the component : " + component + " to " +
              state.label());
```

2024-08-30 16:35 UTC, christophfroehlich commented on controller_manager/src/controller_manager.cpp
> +        "Failed to set the initial state of the component : " + component + " to " + active_state.label());
```suggestion
        "Failed to set the initial state of the component : " + component + " to " +
        active_state.label());
```

2024-08-30 16:37 UTC, saikishor commented
Thank you @christophfroehlich @bmagyar

2024-08-30 16:57 UTC, christophfroehlich approved these changes

2024-10-07 18:32 UTC, bmagyar approved these changes

2024-10-07 18:32 UTC, merged