Propagate read/write rate to the HardwareInfo properly
ros-controls/ros2_control pull request #1928
Opened 2024-12-10 18:10 UTC by saikishor

Alternate approach to https://github.com/ros-controls/ros2_control/pull/1927

Fixes https://github.com/ros-controls/ros2_control/issues/1926

2024-12-10 18:26 UTC, christophfroehlich requested changes
Looks way better! Just needs a test now.

2024-12-10 18:31 UTC, saikishor commented
Moreover, In this approach we remove the const just to modify it, that's why I wasn't sure.

2024-12-10 20:45 UTC, christophfroehlich commented
Ok I see now that we might also add this here to gazebo/gz_ros2_control as we call `parse_control_resources_from_urdf` there.

2024-12-10 22:30 UTC, saikishor commented
> Ok I see now that we might also add this here to gazebo/gz_ros2_control as we call `parse_control_resources_from_urdf` there.

I also thought the same earlier, but in the simulation we use the gazebo hardware directly and it runs at the rate of the simulator, so may be there it is not a big requirement

https://github.com/ros-controls/gazebo_ros2_control/blob/2e242fb7400d8a51f6b5d589d58fb358ce2b5999/gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp#L88-L98

2024-12-13 10:38 UTC, christophfroehlich commented
> I also thought the same earlier, but in the simulation we use the gazebo hardware directly and it runs at the rate of the simulator, so may be there it is not a big requirement

The cm update rate can be lower than that of the simulator. And one could configure a `hw_rate` even lower: as we call the CM in the gazebo update method, this could still work?

2024-12-13 10:38 UTC, christophfroehlich requested changes

2024-12-13 10:38 UTC, christophfroehlich commented on hardware_interface/src/resource_manager.cpp
> +  }
```suggestion
  for (auto & hw : hardware_info)
  {
    hw.rw_rate =
      (hw.rw_rate == 0 || hw.rw_rate > update_rate) ? update_rate : hw.rw_rate;
  }
```

2024-12-13 10:40 UTC, saikishor commented
> The cm update rate can be lower than that of the simulator. And one could configure a `hw_rate` even lower: as we call the CM in the gazebo update method, this could still work?

I believe it should work

2024-12-13 11:23 UTC, saikishor commented
> Ok, but we don't use this method in the gazebo plugin, and if one changes the plugin he has to take care of that..

Yup!

2024-12-20 09:21 UTC, bmagyar approved these changes

2024-12-20 09:21 UTC, merged