Fix the spawner to support full wildcard parameter entries
ros-controls/ros2_control pull request #1933
Opened 2024-12-11 22:52 UTC by saikishor

Fixes #1932

2024-12-11 23:14 UTC, bijoua29 approved these changes
Looks good

2024-12-12 08:11 UTC, christophfroehlich requested changes
The fix seems to be fine (at least what you added in the test makes sense for me). Please add a new example in https://github.com/ros-controls/ros2_control/blob/master/controller_manager/doc/userdoc.rst#spawner

2024-12-12 08:22 UTC, saikishor commented
> The fix seems to be fine (at least what you added in the test makes sense for me). Please add a new example in https://github.com/ros-controls/ros2_control/blob/master/controller_manager/doc/userdoc.rst#spawner

Sure. On it

2024-12-12 08:58 UTC, christophfroehlich approved these changes

2024-12-12 09:19 UTC, merged