add a semantic command interface to "semantic_components"
ros-controls/ros2_control pull request #1945
Opened 2024-12-16 12:40 UTC by tpoignonec

Hi,

Is there any interest in defining a `SemanticComponentCommandInterface` analogous to the `SemanticComponentInterface`, but for hardware command interfaces?

Applications could include, among others, commonly used simple write-only devices such as LED, buzzers, beepers, etc.
It could also be used for GPIO arrays the same way the state interface can be used to read them in a standarized fashion.

This PR includes such a semantic component, as well as a basic example with a 3-channel (R/G/B) LED with two scenarios:
- Default interface names: `<name>/r`,  `<name>/g`, and  `<name>/b`
- Custom interface names using the following syntax:
```cpp
#include "semantic_components/led_rgb_device.hpp"

std::string interface_name_r = "led/custom_r";
std::string interface_name_g = "led/custom_g";
std::string interface_name_b = "led/custom_b";

// Create LED device with custom interface names
auto led_device = std::make_unique<semantic_components::LEDRgbDevice>(
   interface_name_r, interface_name_g, interface_name_b);
```

Additionally, basic tests are proposed.

2024-12-18 19:08 UTC, Wiktor-99 commented
I've thought about it a little bit, and I'm not sure if we should add such a component when the GPIO command controller, which is very generic, is already available

2024-12-18 22:24 UTC, christophfroehlich requested changes
Thanks for the PR including nice tests .
We discussed this shortly in todays WG meeting, and approve this addition. 
I can understand the input @Wiktor-99, but imho
- it is an obvious extension of an existing concept
- it could also use joints and not only gpios
Please add it to the [release_notes](https://github.com/ros-controls/ros2_control/blob/master/doc/release_notes.rst) and some minor comments.

2024-12-19 21:04 UTC, tpoignonec commented
Great!
I do the release note and changes ASAP.

2024-12-20 11:51 UTC, tpoignonec commented on controller_interface/test/test_semantic_component_command_interface.cpp
> +// Copyright 2025 Sherpa Mobile Robotics
I guess let's be optimistic!

2024-12-20 11:52 UTC, tpoignonec commented on controller_interface/include/semantic_components/led_rgb_device.hpp
> +class LEDRgbDevice : public SemanticComponentCommandInterface<std_msgs::msg::ColorRGBA>
Done, but it has to be edited in tests also, so I committed separately

2024-12-22 20:12 UTC, christophfroehlich requested changes
LGTM overall, I just added some comments to be in line with #1940

Maybe you have to format my suggestions once again to satisfy pre-commit.

2024-12-22 20:12 UTC, christophfroehlich commented on controller_interface/include/semantic_components/led_rgb_device.hpp
> +
```suggestion
```

2024-12-22 20:12 UTC, christophfroehlich commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +  ~SemanticComponentCommandInterface() = default;
```suggestion
  virtual ~SemanticComponentCommandInterface() = default;
```

2024-12-22 20:12 UTC, christophfroehlich commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +  }
```suggestion
  SemanticComponentCommandInterface(
    const std::string & name, const std::vector<std::string> & interface_names)
  : name_(name), interface_names_(interface_names)
  {
    command_interfaces_.reserve(interface_names.size());
  }

  explicit SemanticComponentCommandInterface(const std::string & name, size_t size = 0) : name_(name)
  {
    interface_names_.reserve(size);
    command_interfaces_.reserve(size);
  }
```

2024-12-22 20:12 UTC, christophfroehlich commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +    for (size_t i = 0; i < values.size(); ++i)
```suggestion
    for (auto i = 0u; i < values.size(); ++i)
```

2024-12-22 20:12 UTC, christophfroehlich commented on controller_interface/include/semantic_components/led_rgb_device.hpp
> +  }
```suggestion
  explicit LedRgbDevice(const std::string & name)
  : SemanticComponentCommandInterface(
    name, {{name_ + "/" + "r"},
                {name_ + "/" + "g"},
                {name_ + "/" + "b"}})
  {
  }
```

2025-01-02 08:06 UTC, christophfroehlich requested changes
Something still seems to be broken with the tests, can you have a look please?

2025-01-03 18:06 UTC, tpoignonec commented
My bad, hadn't rerun the unit tests after accepting the change suggestions (minor issue with LED constructor).
Should be fine now.

2025-01-03 22:31 UTC, christophfroehlich submitted a review, later dismissed

2025-01-12 22:17 UTC, saikishor requested changes

2025-01-12 22:17 UTC, saikishor commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +   */
Also explain when the false can be 
In this case if the size doesn't match or if the set_value method fails

2025-01-13 01:46 UTC, Raivias requested changes
Other than dropping the library LGTM.

2025-01-13 01:46 UTC, Raivias commented on controller_interface/include/semantic_components/led_rgb_device.hpp
> +#include <limits>
You should be able to remove this package. I'm not seeing it used.

2025-01-13 10:06 UTC, tpoignonec commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +    }
It was done as to maintain symmetry with the `SemanticComponentInterface` :

https://github.com/ros-controls/ros2_control/blob/f4c9dd04116779246cce7c26c5f0cc257adf6d0a/controller_interface/include/semantic_components/semantic_component_interface.hpp#L70-L80

However, it is true that the use case is debatable (in both cases).

2025-01-13 10:15 UTC, saikishor commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +    }
Yup, I agree. As this is the new one that we are introducing, it is better to have it the proper way

2025-01-13 10:31 UTC, tpoignonec commented on controller_interface/include/semantic_components/led_rgb_device.hpp
> +      return false;
Docstring added in commit https://github.com/ros-controls/ros2_control/pull/1945/commits/697bdb79b3e4085e91581b92a4250bd7e12f0a26

2025-01-13 10:36 UTC, tpoignonec commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +   */
Done in commit https://github.com/ros-controls/ros2_control/pull/1945/commits/29cb799095784c045355a1f193defc0224d696f1

2025-01-14 17:05 UTC, saikishor commented
@tpoignonec Can you please fix the pre-commit jobs?

2025-01-16 20:34 UTC, tpoignonec commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +    }
I thought a bit more about it. It is actually (kind of) OK since the `assign_loaned_state_interfaces` function call the getter, so the returned interfaces are always filled:

https://github.com/ros-controls/ros2_control/blob/f4c9dd04116779246cce7c26c5f0cc257adf6d0a/controller_interface/include/semantic_components/semantic_component_interface.hpp#L51-L56

It's not ideal, but at the same time there is no reason, in theory, to overload the `assign_loaned_state_interfaces` method.

The alternative would consist in assigning the default names in the constructor, but that might be tricky to manage, since this constructor is meant to be specialized by child classes that will push into the `std::vector`.
That would mean accessing the interface names by index from the constructor of inherited classes, since the vector would already be filled.

2025-01-17 07:49 UTC, tpoignonec commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +    }
@saikishor  What about declaring the `assign_loaned_state_interfaces` methods as `final`?

2025-01-20 18:15 UTC, saikishor commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +  virtual bool set_values_from_message(const MessageInputType & /* message */) { return false; }
@tpoignonec What do you think about making this pure virtual?

2025-01-20 18:15 UTC, saikishor commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +    }
Sorry for not getting back to you earlier. 

The get_ordered_interfaces  is a helper function and this cannot be set as `final`

https://github.com/ros-controls/ros2_control/blob/54a9226655eb330759cda21d0445e199cb25a53a/controller_interface/include/controller_interface/helpers.hpp#L39-L72

Regarding the  `assign_loaned_state_interfaces`  or  `assign_loaned_command_interfaces`, they are non-virtual methods, adding the `final` here shouldn't change the behaviour much.

I would remove the existing exporting with numbers and add an assert that the interfaces_ variable is not empty or just throw an exception if it is empty within this `get_command_interface_names` method

2025-01-20 18:15 UTC, saikishor commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +  }
Any thoughts about this one?

2025-01-20 18:15 UTC, saikishor commented on controller_interface/include/semantic_components/led_rgb_device.hpp
> +  }
Same here

2025-01-20 18:15 UTC, saikishor commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +  virtual std::vector<std::string> get_command_interface_names()
```suggestion
  virtual const std::vector<std::string> & get_command_interface_names()
```

2025-01-22 14:47 UTC, tpoignonec commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +  virtual bool set_values_from_message(const MessageInputType & /* message */) { return false; }
Sounds good to me, without it it doesn't really make sense.

2025-01-22 14:51 UTC, tpoignonec commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +    }
Agreed, it is good as it forces the programmer to provide appropriate interface names.

The only thing is that there will be no "default" config.
Do you want to also change the state interface one ?

2025-01-22 15:03 UTC, saikishor commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +    }
For the Semantic state interfaces, I would deal this in a different PR, just not to pollute this one. 
As this is something new that we are introducing, it is better that we do it this way

2025-01-22 15:04 UTC, saikishor commented on controller_interface/include/semantic_components/led_rgb_device.hpp
> +  }
If you mean `get_command_interface_names` then yes

2025-01-22 15:17 UTC, tpoignonec commented on controller_interface/include/semantic_components/led_rgb_device.hpp
> +  }
OK, I commit these changes in a few minutes and resolve all current conversations then

2025-01-22 15:43 UTC, tpoignonec commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +  }
OK per the other discussion, see last commit for proposition

2025-01-22 15:48 UTC, tpoignonec commented
@saikishor I removed the constructor as discussed.

At this point, I am even wondering if the `name` variable really serves a purpose.

A typical component would do
```cpp
MyCommandInterface(const std::string & name)
  : SemanticComponentCommandInterface(name, {name + "/my_io_1",  ... , name + "/my_io_N"})
  {
  }
```

However, `SemanticComponentCommandInterface` does not actual use the variable `name_` anymore.

Besides this, LGTM

2025-01-25 13:00 UTC, saikishor submitted a review, later dismissed
LGTM.

Just some minor comments.

2025-01-25 13:00 UTC, saikishor commented on controller_interface/include/semantic_components/led_rgb_device.hpp
> +  : SemanticComponentCommandInterface("", {{interface_r}, {interface_g}, {interface_b}})
```suggestion
  : SemanticComponentCommandInterface(interface_r.substr(0, interface_r.find("/")), {{interface_r}, {interface_g}, {interface_b}})
```

In the constructor, it would be great to check if the first sub string of all these 3 interfaces is the same one. Just not to allow controlling interfaces of different device

2025-01-25 13:00 UTC, saikishor commented on controller_interface/include/semantic_components/semantic_component_command_interface.hpp
> +    assert(!interface_names_.empty());
```suggestion
```
We can remove it, because we are checking it in the constructor

2025-01-27 08:00 UTC, tpoignonec commented on controller_interface/include/semantic_components/led_rgb_device.hpp
> +  : SemanticComponentCommandInterface("", {{interface_r}, {interface_g}, {interface_b}})
Are you sure we want to fail in the constructor?

In that case, we could force the `name` variable to be the prefix:

```cpp
explicit LedRgbDevice(
    const std::string & name, const std::string & interface_r,
    const std::string & interface_g, const std::string & interface_b)
  : SemanticComponentCommandInterface(name,
    {{name + "/" + interface_r}, {name + "/" + interface_g}, {name + "/" + interface_b}})
```

2025-01-27 08:04 UTC, saikishor commented on controller_interface/include/semantic_components/led_rgb_device.hpp
> +  : SemanticComponentCommandInterface("", {{interface_r}, {interface_g}, {interface_b}})
Sure. This makes more sense. Let's go for it

2025-01-27 09:35 UTC, tpoignonec commented on controller_interface/include/semantic_components/led_rgb_device.hpp
> +  : SemanticComponentCommandInterface("", {{interface_r}, {interface_g}, {interface_b}})
https://github.com/ros-controls/ros2_control/pull/1945/commits/e7b078e27e3a60aa9e5d610964df7484fe5046d0

2025-01-27 09:52 UTC, saikishor submitted a review, later dismissed

2025-01-27 09:52 UTC, saikishor commented on controller_interface/include/semantic_components/led_rgb_device.hpp
> +  LedRgbDevice(
```suggestion
  explicit LedRgbDevice(
```

2025-01-27 09:53 UTC, saikishor commented on controller_interface/include/semantic_components/led_rgb_device.hpp
> +  LedRgbDevice(
@tpoignonec FYI

2025-01-27 10:09 UTC, saikishor approved these changes
LGTM.
Thank you @tpoignonec for all the followups.

2025-01-29 21:43 UTC, christophfroehlich approved these changes
LGTM. 

We have an (outdated) list of semantic components here: 
https://control.ros.org/rolling/doc/ros2_control/hardware_interface/doc/hardware_interface_types_userdoc.html#sensors
Where should we put this in the docs (can be a follow-up PR)?

2025-02-03 10:33 UTC, merged