Reuse spawner service clients
ros-controls/ros2_control pull request #1947
Opened 2024-12-16 21:14 UTC by bijoua29

This is an attempt to reduce the overhead and DDS discovery issues associated with starting multiple controllers with the spawner. See https://github.com/ros-controls/ros2_control/issues/1934 for some background.

In this PR, we save off the service client in spawner for reuse for subsequent controllers so we're not creating a new service client for each controller. This change improves the performance and reduces the failures when starting multiple controllers at a time.

There may be a better way to do this so please comment.

Also, this PR conflicts with https://github.com/ros-controls/ros2_control/pull/1944 and may not require that PR anymore.

2024-12-16 21:19 UTC, christophfroehlich reviewed
This seems to be a nice enhancement. Let's see if CI is also happy.

2024-12-16 22:15 UTC, saikishor requested changes
The approach is right, but this restricts all the helper method "node" to be of type `ServiceCallerNode`, I think this is very restricting and better not this way,

2024-12-16 22:23 UTC, bijoua29 commented
> The approach is right, but this restricts all the helper method "node" to be of type `ServiceCallerNode`, I think this is very restricting and better not this way,

Suggestions?

2024-12-16 22:25 UTC, saikishor commented
> Suggestions?

I've an approach. I'm testing now. I'll open a PR if it works fine

2024-12-17 01:55 UTC, bijoua29 commented
Closing this PR as https://github.com/ros-controls/ros2_control/pull/1949 is a better approach

2024-12-17 01:55 UTC, closed without merging