Execute command switch for async hardware components
ros-controls/ros2_control pull request #1951
Opened 2024-12-17 09:49 UTC by trampler

Call `prepare_command_mode_switch` and `perform_command_mode_switch` also on async hardware components. Currently this is not the case as they are stored separately in the resource storage.

2024-12-17 09:57 UTC, saikishor requested changes
Hello!

We are planning to move to the new approach : https://github.com/ros-controls/ros2_control/pull/1567 where this won't be needed. 

Maybe this could be needed for Humble. Do you mind targeting Humble?

2024-12-17 16:59 UTC, saikishor commented
> Sure. No problem. Guess I need to create a new pull request.
> 
> @saikishor Hmm, there are currently no async components in humble. So this pull request doesn't really make sense there.

That's true. okay, let me bring this topic tomorrow in the WG meeting

2024-12-18 09:30 UTC, FranekStark commented
> Hello!
> 
> We are planning to move to the new approach : #1567 where this won't be needed.
> 
> Maybe this could be needed for Humble. Do you mind targeting Humble?

@saikishor Hi, what is the schedule for the refactoring? A the moment the async HW components are not working due to this bug, maybe it would be a good temporary solution to merge in this fix until the big refactoring is done?

2024-12-18 10:02 UTC, saikishor commented
@FranekStark it is already done. The idea is to merge it soon. Sure, let's open this PR again. I would like to discuss with other maintainers and decide on this. Today we have a WG meeting, I'll discuss it there. If you are interested, feel free to join

2024-12-18 18:49 UTC, saikishor commented
Hello!

With @ros-controls/ros2-maintainers we have decided go with the new approach in #1567 instead of going with this fix.

2024-12-19 08:46 UTC, bmagyar commented
I'm closing this PR now but please reopen it if you think it is still relevant.

2024-12-19 08:46 UTC, closed without merging