Give an error output
ros-controls/ros2_control pull request #1969
Opened 2024-12-21 21:47 UTC by christophfroehlich

As we discussed in #1873: On humble we do not take any action if the update call of a controller returns ERROR. As we don't want to break the behavior on humble, I suggest adding at least a log output. 

I'm just not sure if we should just print it once, throttled, or on every call.

Closes #1873

2024-12-21 22:12 UTC, saikishor requested changes
The problem with the `_ONCE` is it will print once for the first controller and will never print it again.

2024-12-21 22:18 UTC, saikishor commented
@christophfroehlich like you. I'm also not sure which is the best option for this. Logging every time might spam a bit, and with throttle might miss some logs. Once might not be a good one here.

2024-12-22 19:54 UTC, christophfroehlich commented
> The problem with the `_ONCE` is it will print once for the first controller and will never print it again.

Ah you are right. I changed it to RCLCPP_ERROR. This will influence the update rate maybe, but this is not a operating mode which should be maintained right?

2024-12-23 15:27 UTC, bmagyar approved these changes
I think it is fair to spam in this case. People should not run with a dead controller :D

2024-12-23 15:27 UTC, merged

2024-12-23 20:19 UTC, saikishor approved these changes

2025-01-22 19:28 UTC, scastro-bdai commented
I for one appreciate the spam, since we just uncovered this :)

https://github.com/frankaemika/franka_ros2/issues/94

2025-01-22 19:37 UTC, saikishor commented
> I for one appreciate the spam, since we just uncovered this :)
> 
> https://github.com/frankaemika/franka_ros2/issues/94

Thank you ;)