Configurable load_controller target_state
ros-controls/ros2_control pull request #246
Opened 2020-11-20 11:23 UTC by v-lopez

Added the option to specify the state of the controller after loading. 
Also added cli options.

For cli there are two implementations that I like.

The current one that can be used as:
`ros2 control load left_arm_controller --target_state inactive` 
As well as the default behavior:
`ros2 control load left_arm_controller` 

The second option is to make the target state argument mandatory:
`ros2 control load left_arm_controller inactive`

2020-11-23 15:01 UTC, destogl requested changes
It looks good as the concept we discussed in the last WG meeting.

During this review, I got another idea...
Why not add simply a new service in CM called `configure_controller`. 
In that case, all these `lifecycle_node` dependencies would vanish.
We keep CM flat and clear., without logic that is not really related to controller management.
To provide a simple user interface, I propose adding additional verbs, e.g. `load_and_configure`, `load_and_activate`, or simply adding flag-logic into cli API.
What do you think?

If we proceed with using flags, I vote for the version with optional flags
```
ros2 control load left_arm_controller --target_state inactive
```

2020-11-24 08:39 UTC, v-lopez commented on controller_manager/src/controller_manager.cpp
> +  const std::string & controller_name, const lifecycle_msgs::msg::State & target_state)
All this load and configure in a service call was done to keep the behavior consistent with ROS1 version.

But if we choose to break that (which I am not against) I would just remove all the configure notions from the ROS2 Control API.

You just need the load/unload/reload services, these manage the creation/destruction of a node within the controller manager. Once a controller node is created, you manage it with the regular lifecycle API.

@bmagyar @Karsten1987 a penny for your thoughts

2020-11-24 08:53 UTC, v-lopez commented on ros2controlcli/ros2controlcli/verb/load.py
> +            choices=['unconfigured', 'inactive', 'active'], default='inactive', required=False)
Yeah, I share your concerns, which reinforces my idea that we should not replicate the work of the lifecycle interface, and just provide load/unload/reload as I mentioned on a comment above.

2020-11-25 08:16 UTC, v-lopez commented on controller_manager/src/controller_manager.cpp
> +  const std::string & controller_name, const lifecycle_msgs::msg::State & target_state)
Ignore my previous message, I am having conflicting thoughts over the whole lifecycle interface for the controllers, I'll try to summarize in an issue so we can discuss it.

2020-11-25 08:44 UTC, v-lopez commented on controller_manager/src/controller_manager.cpp
> +  const std::string & controller_name, const lifecycle_msgs::msg::State & target_state)
https://github.com/ros-controls/ros2_control/issues/249 please take a look

2020-12-15 07:48 UTC, destogl commented
Agreed with @v-lopez to close this in a direct call on Dec, 14th

2020-12-15 07:48 UTC, closed without merging