Fix update rate issues by working around MutliThreadedExecutor
ros-controls/ros2_control pull request #275
Opened 2020-12-18 16:46 UTC by Rayman

Currently the MutliThreadedExecutor performance is very bad. This leads
to controllers not meeting their update rate. This PR is a temporary
workaound these issues.

I've converted the converted the current timer based approach to a
nanosleep approach.

I'm curious what you guys think about this workaround.

2020-12-19 08:22 UTC, bmagyar commented
Could you please elaborate on the effects of this approach?

2020-12-20 08:41 UTC, destogl requested changes
This is related to #260. It seems there is an issue in the depths of `rclcpp` (ros2/rclcpp#1487). There is also a solution that needs some more time... (ros2/rclcpp#1168).

The solution is IMHO legit until this is solved in `rclcpp`.

2020-12-20 08:41 UTC, destogl commented on controller_manager/src/ros2_control_node.cpp
> +  // MutliThreadedExecutor issues are fixes, this loop should be converted back to a timer.
```suggestion
  // When the MutliThreadedExecutor issues are fixed (ros2/rclcpp#1168), this loop should be converted back to a timer.
```

2020-12-20 08:41 UTC, destogl commented on controller_manager/src/ros2_control_node.cpp
> +  // TODO: Due to issues with the MutliThreadedExecutor, this control loop does not rely on the executor. When the
This should restore the CI

```suggestion
  // TODO(anyone): Due to issues with the MutliThreadedExecutor, this control loop does not rely on the executor (see issue #260).
```

2020-12-20 08:41 UTC, destogl commented on controller_manager/src/controller_manager.cpp
> +// deterministic_callback_group_ = create_callback_group(
```suggestion
// TODO(anyone): Due to issues with the MutliThreadedExecutor, this control loop does not rely on the executor (see issue #260).
// deterministic_callback_group_ = create_callback_group(
```

2020-12-20 08:41 UTC, destogl commented on controller_manager/include/controller_manager/controller_manager.hpp
> +  // rclcpp::CallbackGroup::SharedPtr deterministic_callback_group_;
```suggestion
  // TODO(anyone): Due to issues with the MutliThreadedExecutor, this control loop does not rely on the executor (see issue #260).
  // rclcpp::CallbackGroup::SharedPtr deterministic_callback_group_;
```

2020-12-21 14:31 UTC, Rayman commented on controller_manager/src/ros2_control_node.cpp
> +  // MutliThreadedExecutor issues are fixes, this loop should be converted back to a timer.
Done

2020-12-21 14:31 UTC, Rayman commented on controller_manager/src/ros2_control_node.cpp
> +  // TODO: Due to issues with the MutliThreadedExecutor, this control loop does not rely on the executor. When the
Done

2020-12-21 14:31 UTC, Rayman commented on controller_manager/src/controller_manager.cpp
> +// deterministic_callback_group_ = create_callback_group(
Done

2020-12-21 14:31 UTC, Rayman commented on controller_manager/include/controller_manager/controller_manager.hpp
> +  // rclcpp::CallbackGroup::SharedPtr deterministic_callback_group_;
Done

2020-12-21 14:32 UTC, Rayman commented
@bmagyar I've added a simple benchmark to the description

2021-01-06 18:35 UTC, bmagyar approved these changes

2021-01-06 18:38 UTC, merged

2021-01-06 18:38 UTC, Karsten1987 approved these changes

2021-01-13 00:54 UTC, Karsten1987 commented
This PR actually broke the build on OSX.
```
/Users/karsten/workspace/ros2/ros2_control_ws/src/ros-controls/ros2_control/controller_manager/src/ros2_control_node.cpp:53:9: error: use of undeclared identifier 'clock_nanosleep'
        clock_nanosleep(CLOCK_MONOTONIC, 0, &duration, NULL);
``

2021-01-13 12:45 UTC, Rayman commented
Sorry, I did not know OSX was a requirment. Should there be a CI for that?

Good suggestion to replace the call with `std::this_thread::sleep_for`. It should function the same and is more portable.