Fix failing test on rolling
ros-controls/ros2_control pull request #416
Opened 2021-05-14 15:04 UTC by vatanaksoytezer

Fixes the failin rolling test with a specfic macro for MacOS devices. See #406 and #390 .

This will allow ros2_control to compile on rolling

2021-05-14 20:48 UTC, matthew-reynolds requested changes
See https://github.com/ros-controls/ros2_control/issues/406#issuecomment-841494564 for a potential way to avoid duplication of the whole test suite instantiation.

2021-05-17 20:09 UTC, vatanaksoytezer commented
Thanks @matthew-reynolds I think this definitely looks way better! @bmagyar @Karsten1987 I think this should be ready to merge.

2021-05-18 03:13 UTC, tylerjw approved these changes
I tested this locally on rolling and it works for me.

2021-05-18 05:06 UTC, bmagyar commented
Thanks guys!

2021-05-18 05:06 UTC, merged

2021-05-21 15:59 UTC, Karsten1987 commented
Did anybody test this on OSX? This still fails for the exact same reason locally for me as before.

2021-05-21 16:04 UTC, tylerjw commented
> Did anybody test this on OSX? This still fails for the exact same reason locally for me as before.

:cry: I don't think any of us have an OSX setup to test on.  We had assumed this would work because the #define should work the same way it did before on osx.  Is __APPLE__ not the right name to test for?

2021-05-21 16:26 UTC, Karsten1987 commented
The problem is the `,` in the preprocessor directive. I am fairly sure this doesn't work as intended and shouldn't work on gcc either. That's what makes me believe that nobody actually tested this - independently from the OS.

2021-05-21 16:41 UTC, vatanaksoytezer commented
I think a good way to test it would be setup a CI for OSX. I have no way of testing this but I assumed the `APPLE` macro would have worked. If you have a solution to get it working both on OSX and Linux, I think it that would be more valuable since we cannot test this.

2021-05-21 16:41 UTC, Karsten1987 commented
Also, come to think about this. I don't think dividing it via OS is the right approach here in the first place. The issue is that macros are defined differently depending on the gtest version. That gtest version might get updated on OSX as well in future ROS versions. So we'd have to address this `if/else` once again.
We should switch this depending on the ROS distro. If `foxy` then, ...

2021-05-21 20:12 UTC, bmagyar commented
@Karsten1987 I think OSX was dropped to Tier3 from Galactic & onwards

You just said that the gtest version may be different on osx even in foxy, why not try an if based on the gtest version? Worst case we can inject it via the cmake on compilation