Deprecate and rename `start` and `stop` nomenclature toward user to `activate` and `deactivate`
ros-controls/ros2_control pull request #755
Opened 2022-07-02 19:09 UTC by destogl

- Rename fileds and deprecated old nomenclature.
- Remove new defines from SwitchController.srv

2022-07-06 21:27 UTC, bmagyar requested changes

2022-07-07 12:48 UTC, destogl commented on ros2controlcli/ros2controlcli/verb/set_controller_state.py
> +            # TODO(destogl): This has to be implemented in CLI and controller manager
Will open one in parallel and reference to this line.

2022-07-07 20:34 UTC, destogl commented on ros2controlcli/ros2controlcli/verb/set_controller_state.py
> +            # TODO(destogl): This has to be implemented in CLI and controller manager
Addressed in #759

2022-07-08 06:50 UTC, bmagyar commented on ros2controlcli/ros2controlcli/verb/set_controller_state.py
> +            # TODO(destogl): This has to be implemented in CLI and controller manager
thanks!

2022-07-08 06:51 UTC, bmagyar approved these changes

2022-07-08 06:52 UTC, merged