Pr visualize chained controllers
ros-controls/ros2_control pull request #763
Opened 2022-07-03 06:01 UTC by pac48

This change depends on this [PR](https://github.com/ros-controls/ros2_control/pull/758). It adds a new command line option `ros2 control view_controller_chains`, which generates an image using Graphviz.   
![Screenshot from 2022-07-02 23-56-55](https://user-images.githubusercontent.com/28868750/177026947-093920d6-48a2-4b80-883a-d39f81eaaabd.png)

2022-07-04 17:59 UTC, destogl commented
This looks very cool! What do you think that we create a rqt plugin for that?

2022-07-04 18:09 UTC, pac48 commented
> This looks very cool! What do you think that we create a rqt plugin for that?

I was taking inspiration from `ros2 run tf2_tools view_frames.py` described [here](https://docs.ros.org/en/foxy/Tutorials/Intermediate/Tf2/Introduction-To-Tf2.html), but I think an rqt_plugin would also be a good idea.

2022-07-04 22:17 UTC, ejalaa12 commented
That is a very cool feature indeed.
In general a plugin that displays the state of each controller(active, inactive, hardware interface claimed) with features like the one that existed in rqt in Ros1 would be very useful.

2022-07-05 13:04 UTC, pac48 commented
> That is a very cool feature indeed. In general a plugin that displays the state of each controller(active, inactive, hardware interface claimed) with features like the one that existed in rqt in Ros1 would be very useful.

What if I make the lines dashed if the interface is not claimed and solid if it is? And what if I put the controller status (active, inactive) underneath the name at the top of each node?

2022-07-05 13:12 UTC, ejalaa12 commented
> What if I make the lines dashed if the interface is not claimed and solid if it is? And what if I put the controller status (active, inactive) underneath the name at the top of each node?

Agreed for the dashed lines.
I would add a either a small circle (red for inactive, green for active) on the side, or just change the text color, this would be more readable than having an additional text to tell if it is active inactive.

2022-07-30 07:17 UTC, destogl approved these changes

2022-07-30 07:40 UTC, bmagyar approved these changes

2022-08-01 07:07 UTC, bmagyar commented on ros2controlcli/package.xml
> +  <exec_depend>graphviz</exec_depend>
```suggestion
  <exec_depend>python3-pygraphviz</exec_depend>
```

2022-08-01 07:20 UTC, bmagyar commented on ros2controlcli/package.xml
> +  <exec_depend>python3-pygraphviz</exec_depend>
```suggestion
  <exec_depend>python-graphviz-pip</exec_depend>
```

2022-08-02 07:11 UTC, bmagyar commented on ros2controlcli/package.xml
> +  <exec_depend>python-graphviz-pip</exec_depend>
```suggestion
  <exec_depend>python-graphviz-pip</exec_depend>
  <exec_depend>graphviz</exec_depend>
```

2022-08-21 07:43 UTC, bmagyar requested changes
Minor cleanup

2022-08-21 07:43 UTC, bmagyar commented on ros2controlcli/ros2controlcli/verb/view_controller_chains.py
> +# input_chain_connections[controller_name], output_chain_connections
```suggestion
```

2022-08-21 07:43 UTC, bmagyar commented on ros2controlcli/ros2controlcli/verb/view_controller_chains.py
> +    # s.attr(splines="false")
```suggestion
```

2022-08-21 07:43 UTC, bmagyar commented on ros2controlcli/test/test_view_controller_chains.py
> +            chained_from_controller.required_state_interfaces.append(f"joint{i}/position")
```suggestion
            chained_from_controller.required_state_interfaces.append(f"joint{i}/position")
```

2022-08-25 17:00 UTC, bmagyar approved these changes

2022-08-25 19:30 UTC, merged