Add doxygen comments
ros-controls/ros2_control pull request #777
Opened 2022-07-16 21:46 UTC by bmagyar

Pirated the doxygen content from https://github.com/ros-controls/ros2_control/pull/728

2022-07-17 19:13 UTC, destogl requested changes

2022-07-17 19:13 UTC, destogl commented on controller_interface/include/controller_interface/chainable_controller_interface.hpp
> +   * This is the method called in the control loop.
```suggestion
   * Control step update. Command interfaces are updated based on on reference inputs and current states.
   * **The method called in the (real-time) control loop.**
```

2022-07-17 19:13 UTC, destogl commented on controller_interface/include/controller_interface/controller_interface_base.hpp
> +   * This is the method called in the control loop.
```suggestion
   * Control step update. Command interfaces are updated based on on reference inputs and current states.
   * **The method called in the (real-time) control loop.**
```

2022-07-17 19:13 UTC, destogl commented on controller_manager/include/controller_manager/controller_manager.hpp
> +   * \brief      Read from state interfaces
```suggestion
  /// Read values to state interfaces.
  /**
   * Read current values from hardware to state interfaces.
   * **The method called in the (real-time) control loop.**
```

2022-07-17 19:13 UTC, destogl commented on controller_manager/include/controller_manager/controller_manager.hpp
> +   * \brief      Run update on controllers
```suggestion
  /// Run update on controllers
  /**
   * Call update of all controllers.      
   * **The method called in the (real-time) control loop.**
```

2022-07-17 19:13 UTC, destogl commented on controller_manager/include/controller_manager/controller_manager.hpp
> +   * \brief      Write to control interfaces
```suggestion
  /// Write values from command interfaces.
  /**
   * Write values from command interface into hardware.
   * **The method called in the (real-time) control loop.**
```

2022-07-17 21:07 UTC, bmagyar commented
Sehr gut suggestions

2022-08-01 07:14 UTC, bmagyar commented on controller_manager/include/controller_manager/controller_manager.hpp
> +   * Call update of all controllers.
```suggestion
   * Call update of all controllers.
```

2022-08-03 14:16 UTC, destogl approved these changes

2022-08-03 14:20 UTC, merged