pygraphviz functions updated
ros-controls/ros2_control pull request #812
Opened 2022-09-16 06:33 UTC by sachinkum0009

the functions of graphviz are changed to the functions of pygraphviz

2022-09-17 12:41 UTC, bmagyar commented on ros2controlcli/package.xml
> +  <!-- <exec_depend>pygraphviz</exec_depend> -->
```suggestion
  <exec_depend>python-pygraphviz</exec_depend>
```

2022-09-17 18:57 UTC, bmagyar commented on ros2controlcli/package.xml
> +  <exec_depend>python-pygraphviz</exec_depend>
```suggestion
  <exec_depend>python3-pygraphviz</exec_depend>
```

2022-09-18 14:29 UTC, bmagyar requested changes
A few small comments

Also please for future PRs and for git in general try to avoid commit messages such as "minor changes", "fix review comments"

2022-09-18 14:29 UTC, bmagyar commented on ros2controlcli/ros2controlcli/verb/view_controller_chains.py
> +# from PIL import Image
No commented code please

2022-09-18 14:29 UTC, bmagyar commented on ros2controlcli/ros2controlcli/verb/view_controller_chains.py
> +        # s.draw('g.png')
Commented code

2022-09-18 14:29 UTC, bmagyar commented on ros2controlcli/ros2controlcli/verb/view_controller_chains.py
> +    s.draw('/tmp/controller_diagram.gv.pdf', format='pdf')
Why draw it here and not below? That if looks very strange w only `pass` insode

2022-09-18 14:49 UTC, sachinkum0009 commented on ros2controlcli/ros2controlcli/verb/view_controller_chains.py
> +# from PIL import Image
will fix it

2022-09-19 11:57 UTC, bmagyar approved these changes
Thanks very much!

2022-09-19 12:15 UTC, bmagyar commented
for completeness I've uploaded a sample here:

[g.pdf](https://github.com/ros-controls/ros2_control/files/9598741/g.pdf)

yes there are some issues to work out but this PR should get us past the release block

2022-09-19 12:15 UTC, merged