Deprecating class type to plugin name
ros-controls/ros2_control pull request #854
Opened 2022-11-16 12:59 UTC by Robotgir

2022-11-17 17:50 UTC, bmagyar requested changes

2022-11-17 18:01 UTC, bmagyar commented
First note: @Robotgir if you want to revive a PR, the easiest thing to do is to ask the owner of it to give you access to their branch and you can go update it directly. Even if not, it's generally good practice for everyone taking part in the project to mention the PR you are reviving or issue you are addressing. In this case, this PR tries to revive & address some discussions from #780 .

Well... please correct me if I'm wrong but I have the feeling we are the dog chasing it's own tail.

There are 3 breaking changes about renaming `class_type` to `plugin_name` in the various interfaces.
* Renaming the URDF tag name -->  This is user-facing, therefore somewhat sensitive. The good thing is that it's already done :+1: 
* Renaming the member field in `HardwareComponentInfo` --> This is internal API, does not really matter in my opinion.
* Renaming in SRV and MSG files --> This is *highly critical*, since it potentially ties in with existing usercode and tooling using `ros2_control`. 

What I can see in this PR is that deprecation was only done on the part that does not matter at all IMO but the actually breaking changes were made nevertheless.

In this case I suggest simply merging #780 as it's in a better state than this PR.

2022-11-17 18:11 UTC, destogl commented on ros2_control_test_assets/include/ros2_control_test_assets/descriptions.hpp
>  [[maybe_unused]] const std::string TEST_ACTUATOR_HARDWARE_CLASS_TYPE = "test_actuator";
or we should at least rename it? Removing this would break some test (I guess).

2022-11-17 18:33 UTC, destogl commented
> In this case I suggest simply merging #780 as it's in a better state than this PR.

So you think we don't have to deprecate anything because we don't gain anything from it? The major issue is the message that we cannot deprecate, unfortunately.

2022-11-19 08:38 UTC, destogl commented
Closing this in favor of #780 – @bmagyar will finish up this by adding warning of deprecation in ControllerManager

2022-11-19 08:38 UTC, closed without merging