Draft: Make double parsing locale independent
ros-controls/ros2_control pull request #921
Opened 2023-01-23 16:35 UTC by henningkayser

A recent [comment](https://github.com/ros-planning/moveit2/issues/1782#issuecomment-1385826225) in a MoveIt issue made me curious about locale-dependent bugs and runtime flakiness in general. Turns out, parsing doubles with `std::stod` is locale dependent and will silently remove decimals if the parsed text doesn't fit the configured locale. This has been found out and fixed a while ago (see https://github.com/ros/urdfdom/issues/98 for instance), but it still seems to be an issue in several packages, `ros2_control` is just a prominent one and a great example for a start.

2023-01-23 18:36 UTC, destogl requested changes
Thanks for the great PR and detailed explanation. Can you just a do a small cosmetic fix please?

2023-01-23 18:36 UTC, destogl commented on hardware_interface/src/mock_components/generic_system.cpp
> +double parseDouble(const std::string & text)
We are using "snake_case" for methods:

```suggestion
double parse_double(const std::string & text)
```

2023-01-24 17:56 UTC, merged

2023-01-24 17:56 UTC, bmagyar commented
@mergifyio backport to humble

2023-10-06 20:31 UTC, paulm-planted commented
Usage of std::from_chars  requires C++17.  Which is not available on all target hardware platforms.  :(