Create doc fiel for chained controllers
ros-controls/ros2_control pull request #985
Opened 2023-04-10 09:53 UTC by destogl

2023-06-12 16:53 UTC, bmagyar commented
Are you happy with me merging this? People want *some* docs, this is better than nothing!

2023-06-12 17:12 UTC, bmagyar requested changes

2023-06-29 21:40 UTC, christophfroehlich requested changes
I hope this gets merged soon ;)

At least a proper rst markup + pictures and link the file to the docs is needed. (Silently advertising https://github.com/ros-controls/control.ros.org/pull/125). 
Or: Push this file as .md file where the suggested changes are accepted, and I could do the translation to rst then.

2023-06-29 21:40 UTC, christophfroehlich commented on controller_manager/doc/controller_chaining.rst
> +This document proposes a minimal-viable-implementation of serial controllers chaining as described in [Chaining Controllers design document](controller_chaining.md).
I think this one is meant: https://github.com/ros-controls/roadmap/blob/master/design_drafts/controller_chaining.md

2023-06-29 21:40 UTC, christophfroehlich commented on controller_manager/doc/controller_chaining.rst
> +  2. Then "diff_drive_controller" is activated and attach itself to the virtual input interfaces of PID controllers.
```suggestion
  2. Then "diff_drive_controller" is activated and attaches itself to the virtual input interfaces of PID controllers.
```

2023-06-30 21:05 UTC, bmagyar commented on controller_manager/doc/controller_chaining.rst
> +This document proposes a minimal-viable-implementation of serial controllers chaining as described in [Chaining Controllers design document](controller_chaining.md).
Thx

2023-06-30 21:14 UTC, bmagyar commented
@christophfroehlich could we try the docs on this PR?

2023-06-30 21:19 UTC, christophfroehlich commented
this is no valid rst syntax. i'll make an PR against this PR with the changes this weekend

2023-06-30 21:24 UTC, bmagyar commented
Ah yeah I'm aware of that :D was just wondering how far it is. But agree that this should be merged asap

2023-07-01 09:00 UTC, christophfroehlich commented
I refactored it with PR #1068

2023-07-02 17:00 UTC, merged

2023-09-06 09:24 UTC, christophfroehlich commented
@bmagyar this hasn't been backported to humble, which caused the conflicht with #1106. The image and the link in doc/index.rst is missing, see [this error](https://github.com/ros-controls/control.ros.org/actions/runs/6095088775/job/16537947808).

2023-09-29 07:12 UTC, christophfroehlich commented
@destogl can this be backported to humble to fix the build error with the docs for humble?

2023-10-15 12:35 UTC, destogl commented
We have to fix this. The docs is very wrong and misleading in few places...